// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBbtU4WtbAHoxkrqfbhMWhl4oLbWbDruA',
    appId: '1:306604307672:android:7a58b488f63a801e9693ad',
    messagingSenderId: '306604307672',
    projectId: 'expense-tracker-f147a',
    storageBucket: 'expense-tracker-f147a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWnch9xZL8vsICyNaICJN1NxL_oTu8ALc',
    appId: '1:306604307672:ios:9ad9721262e1b4ee9693ad',
    messagingSenderId: '306604307672',
    projectId: 'expense-tracker-f147a',
    storageBucket: 'expense-tracker-f147a.firebasestorage.app',
    iosBundleId: 'com.example.anExpenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWnch9xZL8vsICyNaICJN1NxL_oTu8ALc',
    appId: '1:306604307672:ios:9ad9721262e1b4ee9693ad',
    messagingSenderId: '306604307672',
    projectId: 'expense-tracker-f147a',
    storageBucket: 'expense-tracker-f147a.firebasestorage.app',
    iosBundleId: 'com.example.anExpenseTracker',
  );
}
