name: Flutter

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.32.0"
          channel: "stable"
          cache: true

      - name: Get dependencies
        working-directory: an_expense_tracker
        run: flutter pub get

      - name: Analyze
        working-directory: an_expense_tracker
        run: flutter analyze
